name: palpitate
description: Music Streaming App.


version: 2.3.1+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.4
  audio_manager: ^0.8.2
  new_version: ^0.2.3
  http: ^0.13.3
  shared_preferences: ^2.2.0
  marquee: ^2.2.0
  internet_connection_checker: ^0.0.1+2
  flutter_native_splash: ^1.2.3
  auto_size_text: ^2.1.0
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.2
  flutter_local_notifications: ^9.1.4
  flutter_blurhash: ^0.7.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.3.0
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.1.0
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0+1
  provider: ^6.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Amatic
      fonts:
        - asset: fonts/AmaticSC-Bold.ttf
    - family: Tourney
      fonts:
        - asset: fonts/Tourney-SemiBoldItalic.ttf
  uses-material-design: true
  assets:
    - images/

