name: palpitate
description: A new Flutter application.


version: 2.0.2+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.4
  audio_manager: ^0.8.2
  new_version: ^0.2.3
  http: ^0.13.3
  shared_preferences: ^2.0.6
  marquee: ^2.2.0
  internet_connection_checker: ^0.0.1+2
  flutter_native_splash: ^1.2.3
  auto_size_text: ^2.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Amatic
      fonts:
        - asset: fonts/AmaticSC-Bold.ttf
    - family: Tourney
      fonts:
        - asset: fonts/Tourney-SemiBoldItalic.ttf
  uses-material-design: true
  assets:
    - images/

