name: palpitate
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.18.3
  audio_service: ^0.17.0
  url_launcher: ^6.0.4
  flutter_playout: ^1.0.43
  just_audio: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

